# Docker Compose configuration for Doc Router
# 
# Usage with different profiles:
#   - Default (external mongodb): docker compose up
#   - Local mongodb: docker compose --profile local up
#
# To use different environment settings per profile:
#   - For default: docker compose up                    # Uses .env
#   - For local: docker compose --profile local --env-file .env.local up
services:
  frontend:
    image: analytiqhub/doc-router-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        # Build-time environment
        - NEXT_PUBLIC_FASTAPI_FRONTEND_URL=${NEXT_PUBLIC_FASTAPI_FRONTEND_URL:-http://localhost:8000}
        - NODE_ENV=production
    environment:
      # Runtime environment
      - ENV=${ENV:-dev}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - FASTAPI_BACKEND_URL=${FASTAPI_BACKEND_URL:-http://localhost:8000}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-default_secret_for_development}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXT_PUBLIC_FASTAPI_FRONTEND_URL=${NEXT_PUBLIC_FASTAPI_FRONTEND_URL:-http://localhost:8000}
    command: sh -c "cd /app/frontend && npm run start"
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - doc-router-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend:
    image: analytiqhub/doc-router-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      # Runtime environment
      - ENV=${ENV:-dev}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - FASTAPI_ROOT_PATH=${FASTAPI_ROOT_PATH:-/fastapi}
      - FASTAPI_SECRET=${FASTAPI_SECRET:-default_fastapi_secret_for_development}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SES_FROM_EMAIL=${SES_FROM_EMAIL}
    command: sh -c "cd /app/backend/api && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - doc-router-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  worker:
    image: analytiqhub/doc-router-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      # Runtime environment
      - ENV=${ENV:-dev}
      - N_WORKERS=${N_WORKERS:-1}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - FASTAPI_SECRET=${FASTAPI_SECRET:-default_fastapi_secret_for_development}
    command: sh -c "cd /app/backend/worker && python3 worker.py"
    restart: unless-stopped
    networks:
      - doc-router-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017" # external_port:internal_port
    networks:
      - doc-router-network
    volumes:
      - doc-router-mongodb:/data/db
    profiles: ["local"] # Enable in default and local profiles, but not in external
    command: mongod --quiet --logpath /dev/null
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  doc-router-network:
    driver: bridge

volumes:
  doc-router-mongodb: