services:
  app:
    image: analytiqhub/doc-router:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time variables
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
        - NODE_ENV=production
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      # Runtime-only variables
      - ENV=${ENV:-dev}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    profiles: ["default", "with-mongodb"]

  mongodb:
    image: mongo:latest
    ports:
      # Change to 27018:27017 if you need to avoid conflict
      # with local MongoDB running at default port 27017
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db
    profiles: ["with-mongodb"]

volumes:
  mongodb_data:
