version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # NextJS
      - "8000:8000"  # FastAPI
    environment:
      # Don't use quotes around the variables
      - ENV=${ENV}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    profiles: ["default", "with-mongodb"]

  mongodb:
    image: mongo:latest
    ports:
      # Change to 27018:27017 if you need to avoid conflict
      # with local MongoDB running at default port 27017
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db
    profiles: ["with-mongodb"]

volumes:
  mongodb_data:
