services:
  frontend:
    image: analytiqhub/doc-router-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        # Build-time variables
        - NEXT_PUBLIC_FASTAPI_FRONTEND_URL=${NEXT_PUBLIC_FASTAPI_FRONTEND_URL:-http://localhost:8000}
        - FASTAPI_BACKEND_URL=${FASTAPI_BACKEND_URL:-http://localhost:8000}
        - NODE_ENV=production
    environment:
      # Runtime-only variables
      - ENV=${ENV:-dev}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-default_secret_for_development}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXT_PUBLIC_FASTAPI_FRONTEND_URL=${NEXT_PUBLIC_FASTAPI_FRONTEND_URL:-http://localhost:8000}
    command: sh -c "cd /app/frontend && npm run start"
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - doc-router-network

  backend:
    image: analytiqhub/doc-router-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_for_development}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - FASTAPI_ROOT_PATH=${FASTAPI_ROOT_PATH:-/fastapi}
    command: sh -c "cd /app/backend/api && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - doc-router-network

  worker:
    image: analytiqhub/doc-router-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
    command: sh -c "cd /app/backend/worker && python3 worker.py"

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    networks:
      - doc-router-network
    environment:
      # Update the user/pass
      # In .env, update MONGODB_URI=mongodb://<user>:<pass>@mongodb:27017
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USER:<user>}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASS:<pass>}
    volumes:
      - mongodb_data:/data/db
    profiles: ["with-mongodb"]

networks:
  doc-router-network:
    driver: bridge

volumes:
  mongodb_data: