version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"  # NextJS
    #   - "8000:8000"  # FastAPI
    environment:
      # Don't use quotes around the MongoDB URI
      - MONGODB_URI=mongodb://localhost:27017
      - JWT_SECRET=your_jwt_secret_here
      - ENV=dev
    network_mode: "host"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
