[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "docrouter-sdk"
version = "0.1.0"
description = "SDK for interacting with the DocRouter API"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Analytiq" }
]
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0",
]

[project.urls]
Repository = "https://github.com/analytiq/doc-router"

[tool.hatch.build.targets.wheel]
packages = ["."] 